name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout other repository
        uses: actions/checkout@master
        with:
          repository: visschersm/github-otherrepo
      - name: Run the other action
        uses: ./
        with:
          who-to-greet: "Mona the Octocat"
