name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout other repository
        uses: actions/checkout@master
        with:
          repository: visschersm/github-otherrepo
          token: ${{ github.token }}
          ref: "other-repo"
      - name: Run the other action
        uses: "other-repo"
        with:
          who-to-greet: "Mona the Octocat"
