name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2-beta
        with:
          # Private version of https://github.com/actions/hello-world-docker-action
          repository: visschersm/github-otherrepo
          ref: refs/tags/v1
          token: ${{ secrets.GitHub_PAT }} # `GitHub_PAT` is a secret that contains your PAT to clone that private repo
      - name: Run the private action
        uses: ./
        with:
          who-to-greet: "Mona the Octocat"
