name: first-action
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
      - uses: actions/setup-dotnet@v1
      - name: Setup Node
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v