name: first-action
on: [push]
  jobs:
    test1:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-dotnet@v1
          with: 
            dotnet-version: '3.1.x'
        - run: npm install -g bats
